DROP TABLE IF EXISTS TASK;
DROP TABLE IF EXISTS TASK_LIST;

CREATE TABLE TASK_LIST
(
    id       int AUTO_INCREMENT PRIMARY KEY,
    title     VARCHAR(100) NULL
);

CREATE TABLE TASK
(
    id       int AUTO_INCREMENT PRIMARY KEY,
    list_id  int,
    task     VARCHAR(100) NULL,
    complete BIT NOT NULL DEFAULT 0,
    FOREIGN KEY (list_id) REFERENCES TASK_LIST (id)
);